import { existsSync, writeFileSync } from "node:fs";
import { print, warn } from "../output";

const ENV_LOCAL_TEMPLATE = `# LakeSync configuration
# Generated by: lakesync init

# Gateway URL (self-hosted or Cloudflare Workers)
LAKESYNC_GATEWAY_URL=http://localhost:3000

# Gateway identifier
LAKESYNC_GATEWAY_ID=my-gateway

# JWT secret for authentication
LAKESYNC_JWT_SECRET=dev-secret-change-me
`;

const SYNC_TS_TEMPLATE = `import { createClient } from "lakesync";

// Create a LakeSync client connected to your gateway
const client = createClient({
\tgatewayUrl: process.env.LAKESYNC_GATEWAY_URL ?? "http://localhost:3000",
\tgatewayId: process.env.LAKESYNC_GATEWAY_ID ?? "my-gateway",
\ttoken: process.env.LAKESYNC_TOKEN ?? "",
});

// Define a table schema
await client.defineSchema({
\ttable: "todos",
\tcolumns: [
\t\t{ name: "id", type: "text" },
\t\t{ name: "title", type: "text" },
\t\t{ name: "completed", type: "boolean" },
\t],
});

// Insert data
await client.insert("todos", {
\tid: "1",
\ttitle: "Get started with LakeSync",
\tcompleted: false,
});

// Query data
const todos = await client.query("SELECT * FROM todos");
console.log("Todos:", todos);

// Sync with gateway
await client.sync();
`;

/**
 * `lakesync init` — Set up a new LakeSync project.
 *
 * Creates .env.local and an example sync.ts file in the current directory.
 */
export function init(flags: Record<string, string>): void {
	const force = flags.force === "true";

	// Write .env.local
	const envPath = ".env.local";
	if (existsSync(envPath) && !force) {
		warn(`${envPath} already exists. Use --force to overwrite.`);
	} else {
		writeFileSync(envPath, ENV_LOCAL_TEMPLATE, "utf-8");
		print(`Created ${envPath}`);
	}

	// Write example sync.ts
	const syncPath = "sync.ts";
	if (existsSync(syncPath) && !force) {
		warn(`${syncPath} already exists. Use --force to overwrite.`);
	} else {
		writeFileSync(syncPath, SYNC_TS_TEMPLATE, "utf-8");
		print(`Created ${syncPath}`);
	}

	print("");
	print("Next steps:");
	print("  1. Edit .env.local with your gateway URL and secret");
	print("  2. Generate a token: lakesync token create --secret <secret> --gateway <id>");
	print("  3. Run your sync script: npx tsx sync.ts");
}
